{% set name = "hatch-ci" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: c6f101ac26449a4d02df360faaca6e760c73b54143be98db07776dfffd310804
  patches:
    # this is a one-off patch to allow to build the package (because it is a recursive dependecy)
    - conda.patch

build:
  entry_points:
    - hatch-ci = hatch_ci:script.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.1.0
    - typing-extensions
    - jinja2
  run:
    - python >={{ python_min }}
    - hatchling >=1.1.0
    - typing-extensions
    - jinja2

test:
  imports:
    - hatch_ci
    - hatch_ci.script
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - hatch-ci --help


about:
  home: https://github.com/cav71/hatch-ci
  summary: 'hatch plugin to leverage github for releases'
  description: |
    This provides a plugin to Hatch leveraging a CI/CD system (github at the moment) to deliver packages to PyPi.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cav71
