{% set name = "hatch-ci" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 317e875304ae13f12a44e9cf450f3efc3cdfc2111bf2f7b0279b7e73d267d25e
  patches:
    # this is a one-off patch to allow to build the package (because it is a recursive dependecy)
    - conda.patch

build:
  entry_points:
    - hatch-ci = hatch_ci:script.main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.1.0
    - typing-extensions
    - jinja2
  run:
    - python >=3.8
    - hatchling >=1.1.0
    - typing-extensions
    - jinja2

test:
  imports:
    - hatch_ci
    - hatch_ci.script
  requires:
    - pip
  commands:
    - pip check
    - hatch-ci --help


about:
  home: https://github.com/cav71/hatch-ci
  summary: 'hatch plugin to leverage github for releases'
  description: |
    This provides a plugin to Hatch leveraging a CI/CD system (github at the moment) to deliver packages to PyPi.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cav71
